IF(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)

  SET(LIBROCKET_FOUND TRUE)

ELSE(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)

  SET(ROCKET_FIND_PATHS
        ${DTENTITY_EXT_DEP}/include
        ${DTENTITY_EXT_DEP}/lib
  )
  FIND_PATH(LIBROCKET_INCLUDE_DIR Rocket/Core.h PATHS ${ROCKET_FIND_PATHS})

  FIND_LIBRARY(LIBROCKET_CORE_LIBRARY RocketCore "${ROCKET_FIND_PATHS}")
  FIND_LIBRARY(LIBROCKET_CONTROLS_LIBRARY RocketControls "${ROCKET_FIND_PATHS}")
  FIND_LIBRARY(LIBROCKET_DEBUGGER_LIBRARY RocketDebugger "${ROCKET_FIND_PATHS}")

ENDIF(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)
