# Try to find allegro 5
#
#  ALLEGRO5_SHADER_FOUND - system has allegro5
#  ALLEGRO5_SHADER_INCLUDE_DIR - the allrgo5 include directory
#  ALLEGRO5_SHADER_LIBRARIES - Link these to use allegro5
#

FIND_PATH(ALLEGRO5_SHADER_INCLUDE_DIR allegro5/allegro_shader.h)

SET(ALLEGRO5_SHADER_NAMES ${ALLEGRO5_SHADER_NAMES} allegro_shader allegro_shader liballegro_shader liballegro_shader_static)
FIND_LIBRARY(ALLEGRO5_SHADER_LIBRARY NAMES ${ALLEGRO5_SHADER_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set ALLEGRO5_SHADER_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALLEGRO5_SHADER DEFAULT_MSG ALLEGRO5_SHADER_LIBRARY ALLEGRO5_SHADER_INCLUDE_DIR)

IF(ALLEGRO5_SHADER_FOUND)
  SET(ALLEGRO5_SHADER_LIBRARIES ${ALLEGRO5_SHADER_LIBRARY})
ENDIF(ALLEGRO5_SHADER_FOUND)

MARK_AS_ADVANCED(ALLEGRO5_SHADER_LIBRARY ALLEGRO5_SHADER_INCLUDE_DIR )
