# Try to find allegro 5
#
#  ALLEGRO5_DIALOG_FOUND - system has allegro5
#  ALLEGRO5_DIALOG_INCLUDE_DIR - the allrgo5 include directory
#  ALLEGRO5_DIALOG_LIBRARIES - Link these to use allegro5
#

FIND_PATH(ALLEGRO5_DIALOG_INCLUDE_DIR allegro5/allegro_native_dialog.h)

SET(ALLEGRO5_DIALOG_NAMES ${ALLEGRO5_DIALOG_NAMES} allegro_dialog allegro_dialog_static liballegro_dialog liballegro_dialog_static)
FIND_LIBRARY(ALLEGRO5_DIALOG_LIBRARY NAMES ${ALLEGRO5_DIALOG_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set ALLEGRO5_DIALOG_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALLEGRO5_DIALOG DEFAULT_MSG ALLEGRO5_DIALOG_LIBRARY ALLEGRO5_DIALOG_INCLUDE_DIR)

IF(ALLEGRO5_DIALOG_FOUND)
  SET(ALLEGRO5_DIALOG_LIBRARIES ${ALLEGRO5_DIALOG_LIBRARY})
ENDIF(ALLEGRO5_DIALOG_FOUND)

MARK_AS_ADVANCED(ALLEGRO5_DIALOG_LIBRARY ALLEGRO5_DIALOG_INCLUDE_DIR )
